config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  get 'login' || 'Login' => 'sessions#new'         #changed this from just: " get 'sessions/new' "
  get 'Login' => 'sessions#new'

  post 'login' => 'sessions#create'     #changed this from just: " get 'sessions/create' "
  post 'Login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy' #changed this from just: " get 'sessions/destroy' "

  resources :user

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pets
  
  validates :email,
  presence: true,
  uniqueness: {case_sensitive: false}

  validates :password,
  length: (7..35),
  on: :create

  has_secure_password #ensure's that we are using bcrypt

  def self.authenticate(params)
    User.find_by_email(params[:email]).try(:authenticate, params[:password])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :current_user

  def is_authenticated
    unless current_user
      flash[:danger] = "DANGER WILL ROBINSON (creds invalid)"
      redirect_to login_path
    end
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(user_params)

    if user
      session[:user_id] = user.id
      flash[:success] = "Look what the dern there cow's've'gon'n done drugg'd in"
      redirect_to root_path
    else
      flash[:danger] = "YOU SHALL NOT PASS!"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "To the left, to the left, everything you own..."
    redirect_to login_path
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def index
      @users = User.all
    end

    def create
      User.create(user_params)
      redirect_to root_path
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      puts "editing user"
      u = User.find(params[:id])
      u.update(user_params)
      redirect_to user_path
    end

    def new
      @user = User.new
    end

    def destroy
      puts "user_controller to destroy account"
      u = User.find(params[:id])
      u.destroy
      redirect_to new_user_path
    end

    def show
      puts "user_controller pointing to SHOW ROUTE"
      @user = User.find(params[:id])
    end

    def user_params
     params.require(:user).permit(:name, :email, :password, :firstName, :lastName, :age, :birthday, :phone)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAuthBoilerplate</title>
    <%= csrf_meta_tags %>
    <!-- Bootstrap latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<!-- MUI Junk -->
<link href="//cdn.muicss.com/mui-0.7.5/css/mui.min.css" rel="stylesheet" type="text/css" />
<script src="//cdn.muicss.com/mui-0.7.5/js/mui.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "partials/flash" %>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<h1>Root Route</h1>
<%= link_to "My Profile", user_path(@current_user)  %>
<%= link_to "Edit Profile", edit_user_path(@current_user)  %>
<br>

<p>Name: <%= @current_user.try(:firstName) %>
    <%= @current_user.try(:lastName) %> </p>
<p>Age: <%= @current_user.try(:age) %> </p>
<p>Birthday: <%= @current_user.try(:birthday) %> </p>
<p>Phone Number: <%= @current_user.try(:phone) %> </p>
<p>Email: <%= @current_user.try(:email) %> </p>

<br>

<%= button_to 'logout', logout_path, :method => :delete %>

<%= link_to "logout", logout_path, method: :delete %>

app/views/partials/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <%= value %>
  </div>
<% end %>

app/views/user/edit.html.erb
<h1>Edit Profile</h1>
<%= link_to "home", root_path(@current_user) %>
<%= link_to "My Profile", user_path(@current_user)  %>
<br>

<%= form_for @user do |form| %>

        <div class="row">
            <div class="col-md-12">
                <div class="mui-textfield">
                    <%= form.text_field :firstName, class: 'f', id: 'firstName' %>
                    <%= form.label :firstName, class: '', for: 'firstName' %>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="mui-textfield">
                    <%= form.text_field :lastName, class: 'f', id: 'lastName' %>
                    <%= form.label :lastName, class: '', for: 'lastName' %>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="mui-textfield">
                    <%= form.number_field :age, class: 'f', id: 'age' %>
                    <%= form.label :age, class: '', for: 'age' %>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="mui-textfield">
                    <%= form.date_field :birthday, class: 'f', id: 'birthday' %>
                    <%= form.label :birthday, class: '', for: 'birthday' %>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="mui-textfield">
                    <%= form.text_field :phone, class: 'f', id: 'phone' %>
                    <%= form.label :phone, class: '', for: 'phone' %>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="mui-textfield">
                    <%= form.text_field :email, class: 'f', id: 'email' %>
                    <%= form.label :email, class: '', for: 'email' %>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="mui-textfield">
                    <%= form.password_field :password, class: '', id: 'password' %>
                    <%= form.label :password, class: '', for: 'password' %>
                </div>
            </div>
        </div>

        <%= form.submit 'Submit Changes', :class => 'mui-btn mui-btn--primary' %>
        <%end%>

app/views/user/index.html.erb
<%= form_for :user do |form| %>

    <% @current_user.pets %> 
    
    <% form_for :user do |form| %> 

        <div class="row">
            <div class="col-md-12">
                <div class="mui-textfield">
                    <%= form.text_field :email, class: 'f', id: 'email' %>
                    <%= form.label :email, class: '', for: 'email' %>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="mui-textfield">
                    <%= form.password_field :password, class: '', id: 'password' %>
                    <%= form.label :password, class: '', for: 'password' %>
                </div>
            </div>
        </div>

        <%= form.submit 'SIGN UP', :class => 'mui-btn mui-btn--primary' %>
        <%end%>

app/views/user/show.html.erb
<h1>Show Page</h1>
<%= link_to "home", root_path(@current_user) %>
<%= link_to "Edit Pro", edit_user_path(@current_user)  %>
<br>


<%= link_to "Delete Account", user_path, method: :delete  %>